### ISSUE TITLE
Link to Atlassian "Open Source Project License Request"

### ISSUE THREAD

**Issue by devurandom** [zachflower/awesome-open-source-supporters#11]
Open Source Projects can request a license for Atlassian products, including Confluence. While at least Confluence appears in the list, finding the request form from the link given in the list is not straight forward. Hence I suggest to change the link to: https://www.atlassian.com/software/views/open-source-license-request

**Comment by zachflower** [comment]
Hey @devurandom, that's smart, I'll put some time in the schedule to make sure Atlassian is more accurately represented and properly linked. Thanks for the heads up!
