### ISSUE TITLE
Can all of these organizations continue to be supported in 2021?

### ISSUE THREAD

**Issue by xgdyp** [zachflower/awesome-open-source-supporters#30]
Hello，I'm new to opensource and I'm excited to have discovered this 'treasure' repo. Thanks for your work. And now I want to know if these organizations can still continue to support opensource in 2021?

**Comment by zachflower** [comment]
Hi! To be honest, we don't really know. The list isn't continually audited, but if I get notified of a company that no longer has an "open source" plan I remove them from the list.

**Comment by xgdyp** [comment]
Thanks for your reply!
